version: '3.8'

services:
  mage:
    image: mageai/mageai:latest
    container_name: mage
    command: mage start my_pipeline
    ports:
      - "6789:6789"
    volumes:
      - .:/home/src/
    environment:
      - USER_CODE_PATH=/home/src

  mlflow:
    build:
      context: .
      dockerfile: mlflow.dockerfile
    ports:
      - "5000:5000"
    volumes:
      - "${PWD}/mlflow_data:/home/mlflow_data/"

